### ISSUE TITLE
Live Single Immune panel 2

### ISSUE THREAD

**Issue by ztflaten** [PankratzLab/auto-fcs#65]
H bound at 130k and W bound at 150k to exclude 'odd' samples

![image](https://user-images.githubusercontent.com/33128106/33094600-57637560-cec6-11e7-9048-b463f5ffc1d7.png)

Good example

![image](https://user-images.githubusercontent.com/33128106/33094619-6a9ed6f6-cec6-11e7-8e47-7532f455b981.png)

**Comment by jlanej** [comment]
Added boundary with parameters `min=c(0,0),max=c(1.5e5,1.3e5)` 

Looks like this will trim a small amount off the -H axis, rarely trim the -W, and should help with the "odd" samples above. 
<img width="886" alt="screen shot 2017-11-21 at 4 13 10 pm" src="https://user-images.githubusercontent.com/6052453/33099721-6de5c44e-ced7-11e7-8639-684d38640442.png">
<img width="886" alt="screen shot 2017-11-21 at 4 15 26 pm" src="https://user-images.githubusercontent.com/6052453/33099720-6dc36566-ced7-11e7-9d9e-39e225677047.png">

**Comment by erincassidy** [comment]
Looking through the Live Single immune cell gate for r23... It looks like you set the max value of these axes to where we wanted the max values of the gates to be (we were looking to set the max value of the x and y gates ~150k). The range of the axes should still be the same so that we can make sure the gate is where it needs to be. 

![image](https://user-images.githubusercontent.com/33880355/33288227-21f4624e-d381-11e7-9d6a-4a83c440d4c0.png)

![image](https://user-images.githubusercontent.com/33880355/33288348-8c87f4d6-d381-11e7-9201-41d61da45c1f.png)

The above two images look like they're probably trimmed at the right spot but without the whole picture its hard to tell. Let us know if that makes sense.

**Comment by jlanej** [comment]
Cool, I think I understand - maybe something like the below 
<img width="886" alt="screen shot 2017-11-27 at 3 39 22 pm" src="https://user-images.githubusercontent.com/6052453/33290754-4e3d919c-d389-11e7-9ca9-db5a9ca3415f.png">

where the bold red rectangle represents the final Live Single immune cell gate that incorporates the initial gating and the hard-trimmed gate all in one?

**Comment by ztflaten** [comment]
Yes, I would have the gate where the bolded red box is but would still want to see the full 'field' if that makes sense.

**Comment by jlanej** [comment]
Cool sounds good - I can talk to @rcoleb to figure out the best way to display these. The bold-red example would require boolean gating, or we could simply plot the initial gate like the previous openCyto examples.

Step1 - (initial gate) tailgate 
<img width="886" alt="1" src="https://user-images.githubusercontent.com/6052453/33291188-9b27f186-d38a-11e7-952d-0b1907ac4b46.png">
Step2 - trim outliers 
<img width="886" alt="2" src="https://user-images.githubusercontent.com/6052453/33291189-9b35f8b2-d38a-11e7-8e4a-7f6e844269b4.png">
