### ISSUE TITLE
Lymphocyte gate

### ISSUE THREAD

**Issue by erincassidy** [PankratzLab/auto-fcs#77]
The lymphocyte gate needs to be tightened. This seems to only occur in a small percentage of samples (~14 samples/ 352 viewable samples in r24) but needs to be fixed.

![image](https://user-images.githubusercontent.com/33880355/33337152-ae050502-d437-11e7-833a-90983f4e1abe.png)

![image](https://user-images.githubusercontent.com/33880355/33338515-f0924bec-d43b-11e7-83a0-376edda2d8a9.png)

![image](https://user-images.githubusercontent.com/33880355/33339420-ae873d22-d43e-11e7-8889-1f77abb5767a.png)

**Comment by jlanej** [comment]
Prior:

<img width="886" alt="screen shot 2017-11-28 at 3 14 52 pm" src="https://user-images.githubusercontent.com/6052453/33344539-ed8e3c72-d44e-11e7-9c70-0a3f1e875704.png">
<img width="886" alt="screen shot 2017-11-28 at 3 13 23 pm" src="https://user-images.githubusercontent.com/6052453/33344540-ed9ce006-d44e-11e7-8f95-7d578480ce47.png">
<img width="886" alt="screen shot 2017-11-28 at 3 12 45 pm" src="https://user-images.githubusercontent.com/6052453/33344541-edadd60e-d44e-11e7-9a8c-5d2072bb0aaf.png">

**Comment by jlanej** [comment]
Was able to get these particular samples in check a bit more with a more stringent SSC-A boundary filter, and reducing the quantile capture target from .90 to .85. Will test internally, and then submit for review since this is a pretty primary gate. 

<img width="886" alt="screen shot 2017-11-28 at 4 01 57 pm" src="https://user-images.githubusercontent.com/6052453/33346501-95ac4222-d455-11e7-9a19-c3fb3a6e951a.png">
<img width="886" alt="screen shot 2017-11-28 at 4 00 13 pm" src="https://user-images.githubusercontent.com/6052453/33346502-95bb0b36-d455-11e7-81a8-e2227d9725a3.png">
<img width="886" alt="screen shot 2017-11-28 at 3 58 57 pm" src="https://user-images.githubusercontent.com/6052453/33346503-95d3865c-d455-11e7-96e0-69439c103d3b.png">

**Comment by jlanej** [comment]
Update did not work well for LSR (above 3 files are fortessa) - may transition to machine specific parameters

**Comment by erincassidy** [comment]
Most of the lymphBcellTest_77_67 look good.

Not sure what happened but the three samples I gave above are still gated incorrectly? Here's what these IDs look like from lymphBcellTest_77_67:   

![image](https://user-images.githubusercontent.com/33880355/33387797-d6dac0b8-d4f3-11e7-8e4c-fa5026a0fce5.png)

![image](https://user-images.githubusercontent.com/33880355/33387806-dda81a12-d4f3-11e7-9022-bfd183de1575.png)

![image](https://user-images.githubusercontent.com/33880355/33387809-e323770c-d4f3-11e7-9ea3-5b4846c1ce2b.png)

**Comment by jlanej** [comment]
I tested the three examples locally and all looked good, but I don't think they were actually included in the lymphBcellTest_77_67 batch ?

**Comment by erincassidy** [comment]
Disregard the post above (I was not actually looking at lymphBcellTest_77_67). lymph gate looks great in the lymphBcellTest_77_67 batch. Below are the only IDs I would modify the gate in and one of them is an abnormal sample:
 
F1632269
F1641949 (weird sample)
F1635083

I think this issue can be closed.
